raise error upon broken link

diff --git a/.github/workflows/check-links.yml b/.github/workflows/check-links.yml
--- a/.github/workflows/check-links.yml
+++ b/.github/workflows/check-links.yml
@@ -21,4 +21,11 @@ jobs:
 
       - name: Find Markdown Files and Check Links
         run: |
-          find . -name '*.md' -exec markdown-link-check {} \;
+          find . -name '*.md' | while read line; do
+            echo "Checking $line"
+            markdown-link-check "$line" --config .github/markdown-link-check-config.json
+            if [ $? -ne 0 ]; then
+              echo "::error ::Broken links detected"
+              exit 1
+            fi
+          done
